server:
  port: 8099

spring:
  servlet:
    multipart:
      location: /Users/pengchen/PENGCHEN/DemoProject/demo-action/files
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
            dataSource: quartzDataSource
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
          dataSource:
            quartzDataSource:
              URL: jdbc:mysql://localhost:3306/test #URL要大写
              user: root
              password: 123456
              driver: com.mysql.cj.jdbc.Driver
              maxConnections: 5

  redis:
    database: 0
    host: 172.17.0.5
    port: 6379
    password:
    jedis:
      pool:
        min-idle: 0
        max-total: 8
        max-idle: 8
        max-wait: -1
    connect-timeout: 30000

  banner:
    charset: utf-8
    location: classpath:banner.txt
  main:
    banner-mode: console

elasticsearch:
  uris:
  - http://127.0.0.1:9200
  read-timeout: 30
  connection-timeout: 3000
  prefix: demo_
  suffix: _index
  baseName: elasticsearch

logging:
  level:
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
